#!/usr/bin/env bash

# basic loop in bash
# for thing in list or array 'foo bar baz bat' is a list
# ; do tells bash that we are opening up a loop
# done tells bash that the loop is complete
for thing in foo bar baz bat; do
  echo "thing is $thing"
done

echo -e "\n##########################################################################################################\n"

# '; do' is not required, it just lets us write do on the same line as the for statement
# we could write
for thing in foo bar baz bat
do
  echo "thing is $thing"
done

# this will print
# thing is foo
# thing is bar
# thing is baz
# thing is bat

echo -e "\n##########################################################################################################\n"

# this will loop over the argurments given when executing the script. the limit here is 3, if 4 arguments are provided then it will be lost
# for thing in "$1" "$2" "$3"; do
#   echo "thing is $thing"
# done

for thing in "$@"; do
  echo "thing is $thing"
done
